# Generated by Django 6.0.2 on 2026-04-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phobe_number',
            new_name='phone',
        ),
    ]
