# Generated by Django 6.0.2 on 2026-04-24 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='change_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='task.task'),
        ),
    ]
