# Generated by Django 6.0.2 on 2026-04-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskhistory_change_details_taskhistory_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
