# Generated by Django 6.0.2 on 2026-04-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_taskhistory_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
